version: '3'

services:
  database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: movies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_NAME: movies_db
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  postgres_data: